Dynatrace/dynatrace-configuration-as-code-core

api/clients/buckets/bucket.go, api/clients/buckets/bucket_test.go, api/clients/factory.go, api/rest/client.go, api/rest/client_test.go, api/rest/rate.go, internal/testutils/testcontext.go
As one of the main users of this library monaco relies on structured logs with slightly
different fields for each call to the api clients, setting a logger only once when constructing
a client is not practical.
Instead of allowing to set the logger but exporting it so users could manually edit it when needed,
we opt for a pattern of viewing logging as an optional sideffect and transporting loggers inside a context.
Using logr functions we attempt to read the logger from the context and if none exists simply discard all
log calls.
=> refactor: Replace logger struct fields with logger from context 

api/clients/factory.go
Adds the possibility to set an "User-Agent" via the provided client factory.
Also, the struct name was changed to just `factory` instead of `clientFactory`
Further, accessing the factory is now just possible via an exported `Factory()` function
=> feat: add WithUserAgent to factory

api/clients/buckets/bucket.go
In e2e tests we saw that 3 retires were not enough and one of the bucket tests fails occasionally, hence this number is slightly increased to 5. Maybe we should also think about making this configureable
=> fix: Bucket CLient increase fixed retries from 3 to 5

api/clients/buckets/bucket.go, api/response.go, api/response_test.go, api/rest/client.go, api/rest/client_test.go, api/rest/response.go
Often you want to treat API responses (4xx,5xx) as a real go error. I've introduced the AsAPIError method on response which enables just that.
```go
if err, ok := response.AsAPIError(); ok {
//do something wit api err
}
```
=> feat: add possibility to convert an Response into an APIError

.github/CODEOWNERS
Previously this was set to the maintainer group for monaco, but a new shared group of config-as-code tooling maintainers exists and is better suiter as reviewers for this repo.
=> chore: Update codeowners to shared maintainer group

README.md, api/clients/automation/automation.go, api/clients/automation/automation_test.go, api/clients/buckets/bucket_test.go, api/clients/factory.go, api/clients/factory_test.go, api/response.go, api/response_test.go, api/rest/client.go, internal/testutils/testserver.go
This PR introduces a new client targeting the automation API. It provides support for workflows, business-calendars, and scheduling rules.
The client can be obtained via the factory as usual and offers CRUD + Upsert operations.
I have not yet added logging to the client.
This is planned for a follow-up PR to solely focus on useful logs.
Yes, user has access to new automation client, e.g. via the existing factory:
```go
client, err := factory.AutomationClient()
if err != nil {
// handle err
}
```
from here on you can call the desired operation on the client, e.g. getting an existing workflow:
```go
response, err = automationClient.Get(context.TODO(), automation.Workflows, id)
if err != nil {
panic(err)
}
if err, isAPIErr := response.AsAPIError(); isAPIErr {
panic(err)
}
....
```
=> feat: introduce api client for automation resources

api/clients/automation/automation.go, api/clients/automation/automation_test.go, api/response.go, api/response_test.go
This fixes two issues accidentally introduced when the client was moved from monaco. 
It also adds some convenience methods for PaginatedListResponse, which were found missing when re-integrating the client into monaco.
=> fix(automation): Correctly handle offset based pagination & adminAccess query parameter

api/clients/automation/automation.go, api/clients/buckets/bucket.go, api/clients/buckets/bucket_test.go
Although achieving uniformity across all clients' interfaces may not be practical, standardizing the return signature can be easily accomplished. This simplifies the usage of the client(s) and enhances convenience.
Moreover, these changes support the flexibility to not break any code once an API suddenly introduces pagination.
:exclamation: Return types are different, thus clients need to adopt the usage.
=> refactor: unify return types of clients

.github/workflows/build-test.yml, .github/workflows/dependencies-and-licenses.yml, .github/workflows/pr-static-code-analysis.yml, go.mod
Updates go.mod and Workflows to use go 1.22
=> chore: Update go version to 1.22.0

README.md, api/clients/documents/documents.go, api/rest/client.go, api/rest/client_test.go, clients/documents/documents.go, clients/documents/documents_test.go, clients/factory.go, clients/factory_test.go, testutils/testserver.go
This PR introduces the http client for document support.
We've discussed a bit about our current approach of returning errors **only** if any HTTP call did not work.
While this is fine for the basic clients (which only make single http requests) it is a bit awkward for smart clients that have methods like e.g. Upsert which involves multiple HTTP calls.
I've [changed](https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/91/commits/08d8e469c1d76fecafd7082471641a5098426b23) the code so that errors are also returned in case of api errors (return codes != 2xx). In this case an APIError value and a zero value'd Response is returned
In a follow-up the existing smart clients for automation and buckets should be changed accordingly)
=> feat: document client

api/response.go, clients/buckets/bucket.go, clients/buckets/bucket_test.go
**What this PR does / Why we need it:**
To align this client with the newly created document client (https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/91), this PR changes the way the bucket client behaves in error cases.
Instead of always returning a response, it now returns an `APIErrorerror` type in case the API request resulted in a HTTP error status != 2xx.
Errors that occur during reading the body currently do not include a status code, however this is something we may address in a follow-up ticket.
=> chore: Update bucket client to return API errors

clients/automation/automation.go, clients/automation/automation_test.go
To align this client with the newly created document client (https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/91), this PR changes the way the client behaves in error cases.  
Instead of always returning a response, it now returns an `APIError`error type in case the API request resulted in a HTTP error status != 2xx.
=> chore: Update automation client to return API errors 

clients/documents/documents.go, clients/documents/documents_test.go
This PR adds support for `isPrivate` to `documents.Client`, adding it to `documents.Response` and to the parameters of the create and update methods.
=> feat: Add `isPrivate` field to documents client

api/response.go, api/response_test.go, api/rest/client.go, api/rest/reader.go, api/rest/response.go, clients/factory.go, clients/factory_test.go
This PR extends the clients factory with the ability to create REST clients directly, but more importantly, clients that can target classic APIs (with access token). It also adapts the creation of accounts clients to be more consistent.
It also adds a helper function `AsResponseOrError(...)`,  which should be used to consistently read and close the response body and allow for easier error handling.
Calling this returns EITHER a `Response` with the read body and a successful status OR an error, which could be an `APIError` if a response was actually received. This can simplify e.g. error handling for skipping 404s during deletion to something like:
```
_, err = coreapi.AsResponseOrError(d.classicClient.DELETE(ctx, parsedURL.String(), corerest.RequestOptions{}))
if err != nil {
apiError := …
```
=> feat: Allow client factory to create REST clients

api/response.go, api/rest/client_test.go, api/rest/rate.go, clients/factory.go
This PR:
- fixes issue where headers were not being copied into responses, 
- exposes the rate limiter and request retrier to consumers of `client.Factory`, and
- changes the default rate-limit timeout to 10 seconds
=> feat: Add rate limiter and request retrier to factory

api/rest/client_test.go, api/rest/rate.go
This PR reduces the default timeout in rate limiter to 100 ms.
=> chore: Use minimal default timeout in rate limiter

api/clients/automation/automation.go, api/clients/buckets/bucket.go, api/clients/documents/documents.go, api/rest/client.go, api/rest/client_test.go, api/rest/retry.go, clients/factory.go
This PR simplifies overriding retry behavior to just providing the "should retry function" rather than the whole RequestRetrier structure. This is useful because it makes it easy to change the retry behavior without knowledge of the delay or maximum number of retries.
The PR also adjusts the retry behavior of the clients:
- essentially turning it off for buckets - this client has its own retry implementation - only retry for `StatusTooManyRequests`
- for automation client:
- if doing an "admin access" request, no retrying occurs if `StatusForbidden` is returned,
- if deleting, no retrying occurs if `StatusNotFound` is returned.
- for documents client, if deleting, no retrying occurs if `StatusNotFound` is returned
=> feat: Simplify overriding retry behavior of REST client

api/rest/client.go
In https://github.com/Dynatrace/dynatrace-configuration-as-code-core/blob/main/api/rest/client.go, `func (c *Client) sendWithRetries(...)` calls itself recursively, but (tries to) acquire a lock each time. This causes the function to deadlock.
Proposed solution is to only acquire this lock once, outside of `sendWithRetries(...)`.
Only issue is that the rate limiter may sleep once it acquires the lock, but as this is shared by all goroutines accessing the client, this should have no impact.
=> fix: Acquire lock once outside of sendWithRetries

api/rest/client_test.go, api/rest/rate.go
Treat `X-RateLimit-Reset` header values as Seconds. (unix timestamp)
=> Fix units used for rate limit headers

clients/openpipeline/openpipeline.go, clients/openpipeline/openpipeline_test.go
During an update, set the updateToken accordingly. 
To update an OpenPipeline configuration, the `updateToken` must be either empty or set to the latest version. To be consistent with existing code, we set the `updateToken`.
No
=> fix(OpenPipeline): Set `updateToken`

api/clients/grailfiltersegements/filtersegments.go, api/clients/grailfiltersegements/filtersegments_test.go, api/response.go, clients/factory.go, clients/grailfiltersegments/export_test.go, clients/grailfiltersegments/filtersegment_test.go, clients/grailfiltersegments/filtersegments.go
This PR introduces the http client for grail filter segments to be used by monaco and terraform.
=> feat: grail filter segments client

api/clients/segements/segments.go, api/clients/segments/segments.go, api/clients/segments/segments_test.go, clients/segments/segment_test.go, clients/segments/segments.go
This PR suggests a few minor changes to the segments client found while reviewing other code in the area:
-  makes several error messages more consistent
- fixes a typo in segments package name
- moves checks for empty IDs to the segments API client
=> refactor: Improve segments clients

clients/documents/documents.go, clients/documents/documents_test.go
The client now allows arbitrary types to be set. It's the consumer's responsibility to restrict the types that can be used. There is no change in functionality, as consumers already could use this by casting an arbitrary string to the `DocumentType` type.
=> feat(documents): Allow arbitrary document types

clients/documents/documents_test.go, clients/documents/metadata.go
This PR adds `originAppId` to `documents.Metadata`, as needed for https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1674
=> feat: Support `originAppId` in document metadata

gen/account_management/model_external_service_users_page_dto.go, gen/specs/account_management/spec_formatted_fixed.json
This PR manually fixes the generated account management client to make `nextPageKey` for `ExternalServiceUsersPageDto` optional, important for the last page of results.
=> fix: Make `NextPageKey` in `ExternalServiceUsersPageDto` optional

api/clients/segments/segments_test.go, clients/segments/segment_test.go, clients/segments/segments.go
Split segments `upsert` into `create` and `update` to enable usage for Terraform and keep consistency with other implementations of clients.
=> chore(segments): split segments `upsert` into `create` and `update`

clients/factory_test.go
This PR includes test cases that cover slo and segment factory functions in the `factory.go`.
=> test: add test cases for segment and slo factory

gen/account_management/api_service_user_management.go, gen/specs/account_management/spec_formatted_fixed.json
This PR manually updates the spec and runs the generator to make `page` and `pageSize` an integer `int32` (rather than a number ending up as a `float32`).
=> fix: Make service user page and page size integer

.github/workflows/build-test.yml, .github/workflows/dependencies-and-licenses.yml, .github/workflows/pr-static-code-analysis.yml, go.mod
Updates go (lib and pipeline) to `1.24`
=> chore: Update Go to version 1.24

api/clients/segments/segments_test.go, api/rest/client_test.go, clients/factory.go, clients/factory_test.go, clients/segments/segment_test.go, clients/slo/slo_test.go, testutils/testcontext.go
Forwards the correct context to all places
=> chore: pass right context

clients/buckets/bucket.go
The overall aim of this PR is to work towards making the buckets client easier to understand, primarily by making use of `api.NewResponseFromHTTPResponse(...)`. It should:
- handle reading and closing of HTTP response bodies correctly
- reduce the amount of code in the client.
Furthermore, I suspect that handling responses correctly should help the stability of the E2E tests, and ultimately of the client.
While I prefer `api.AsResponseOrError(...)` to `api.NewResponseFromHTTPResponse(...)` as it saves even more code, we seem to be moving away from that and it doesn't fit so well with the current method signatures of the client.
The PR is broken up into several commits; code should still compile and tests should pass after each one, as the functionality should remain the same.
=> refactor: Buckets client to use `api.NewResponseFromHTTPResponse(...)`

api/rest/client.go, api/rest/client_test.go, api/rest/retry.go, api/rest/retry_test.go
Ignore certain status codes that should not be retried (e.g., 403), because they will always fail
=> chore: ignore 403 on retry

clients/buckets/bucket.go, clients/buckets/bucket_test.go, clients/factory.go
This PR removes the unused `maxRetries` from buckets client retry settings.
=> refactor: Remove unused `maxRetries` from buckets client

.github/workflows/pr-static-code-analysis.yml
This PR introduces a pined version for golangci_lint.
=> fix: Add `golangci_lint_version` to pin version

clients/buckets/bucket.go, clients/buckets/bucket_test.go
This PR ensures that all log messages generated by the buckets client include the bucket name.
=> refactor: Bucket client logs should include bucket name

gen/account_management/api_service_user_management.go, gen/specs/account_management/spec_formatted_fixed.json
This PR manually updates the spec to add a return type for GET `/iam/v1/accounts/{accountUuid}/service-users/{userUuid}` and  updates the generated code.
The return type was added in response to what the API actually returns.
=> fix(account): Add return type to `func (r ApiGetServiceUserRequest) Execute()`

gen/account_management/model_external_service_user_with_group_uuid_dto.go, gen/specs/account_management/spec_formatted_fixed.json
By manually updating the account management spec and making `GroupUuid` within `ExternalServiceUserWithGroupUuidDto` optional, the generated client is able to handle service users without a group uuid set, which currently (still) exist in production environments. 
As this field is currently not being used, this has no consequence for Monaco.
=> fix(account): Make `groupUuid` of `ExternalServiceUserWithGroupUuidDto` optional

.github/workflows/build-lint-test.yml
Regarding golangci-lint:
The golangci-lint action is from the maintainers of golangci-lint; it's the suggested way to use golangci-lint, and because of some incidents in the past, Reviewdog should not be used.
Regarding reporting:
Because Sonar does its reporting, we don't need our lint action to report (and fail) an additional time. Therefore, it's enough if the lint report is generated, which is everything Sonar needs. This also adds the ability to ignore specific errors that are reported not to occur again, once ignored.
- Reviewdog is now removed, and the golangci-lint action is used instead.
- The double reporting is gone, and Sonar will only be reporting.
- Using the golangci-lint action.
- Adding an argument not to fail the pipeline if there are any errors.
- Removing the GitHub …
=> ci: use golangci-lint and remove double lint reporting

api/rest/client.go, api/rest/client_test.go, internal/pointer/pointer.go
Specific clients in Monaco CLI, like settings and config clients, have different retry logic. If the core retry logic should be used, the retry options for CRUD calls need to be extended. Therefore, CRUD requests now accept a custom delay and max retry amount, which is preferred over the client-set one.
Should we create a follow-up to move the request options into a struct? Note that the `RequestOptions` struct can't be reused because we must differentiate between empty value and nil (for example, zero retries or zero delay). Changing it to a struct also means a breaking change for the Monaco CLI (not for Terraform, as this is not used on their side).
- No breaking change for consumers of the lib
- Retry delay and max retry amount can now be set on CRUD operations
=> feat: support custom retry delay and amount for rest client calls

clients/settings/permissions/errors.go, clients/settings/permissions/errors_test.go, clients/settings/permissions/permissions.go, clients/settings/permissions/permissions_test.go
The main goal of this commit is to add the client code for the settings object permission handling API.
This code can then be used by both, the dynatrace-configuration-as-code project and the Terraform provider.
Yes, a new client for managing settings object permissions is provided.
=> feat(settings): Adding settings object permission client

.github/workflows/e2e-test.yaml, api/auth/auth_e2e_test.go
We currently do not have any tests that test the 'real' behavior of the core library. We would not notice that an authentication method is broken until a consumer uses the library and notices it. 
This PR changes that. We introduce e2e tests that are executed
* nightly
* on `main`
* on branches with the `run-e2e-test` label
I suggest the following rules:
* No e2e test folder - put the e2e tests in the same directory as the functionality.
* The `e2e` tests must include the `e2e` built tag
Workflows with the `pull_request_target` are dangerous to use. 
They are executed in the context of the target repository; thus, an attacker could create a PR to read all secrets in our repository.
We mitigate this issue by requiring the `run-e2e-test` label.
This label can only be set by maintainers and …
=> test: Introduce end-to-end tests

clients/buckets/statuscheck.go, clients/buckets/statuscheck_test.go
`AwaitBucketStable` may not tell what exactly it's doing at first glance, therefore renaming it to `AwaitActiveOrNotFound`
=> refactor(bucket): rename `AwaitBucketStable` to `AwaitActiveOrNotFound`

.github/dependabot.yml
`reviewers` is no longer supported in `.github/dependabot.yml` as `CODEOWNERS` is used instead as described in https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
Removes both instances of `reviewers` from `.github/dependabot.yml`
Not required
No effect
**Issue:** NOISSUE
=> chore: Remove `reviewers` from dependabot config

clients/settings/permissions/permissions.go
Because there aren't any other request options or adjustments, the name `getRequestOptions` is sufficient.
Addresses: https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/240/files#r2225494470
`getDefaultRequestOptions` => `getRequestOptions`
Current tests cover it.
Doesn't affect users
=> refactor(permissions): rename `getDefaultRequestOptions`

clients/documents/documents.go, clients/documents/documents_test.go, clients/documents/metadata.go
This PR adds `originExtensionId` to `documents.Metadata`. This field, together with `originAppId` allows ready-made documents to be identified, which cannot be modified.
-The `documents.Metadata` struct is updated.
-The `documents.List(...)` method now requests the `originExtensionId` field be included in results. No change is required for `documents.Get(...)` as `originExtensionId` is always returned in the GET responses.
Existing tests are updated.
None.
**Issue:** CA-16532
=> feat(document): Support `originExtensionId` in metadata
