Dynatrace/dynatrace-configuration-as-code-core

api/clients/buckets/bucket.go

Fixes a debug message:
debug   [coord=project:bucket:my-bucket][gid=0] Failed to create new object with bucket name "project_bucket_my-bucket". Trying to update existing object. Error: **%!s(<nil>)**

fix: fix error shown in debug message

---

api/clients/factory_test.go

add basic unit tests to cover factory code

test: cover factory with unit tests

---

README.md

Adds a section `API Clients` to the README.md file describing what it supports and how to use it

doc: Add API Clients section to README

---

README.md

Update `README.md` to describe newest features of lib.

Doc: update `README.md` with example showing how to use HTTPListener

---

README.md
api/clients/buckets/bucket.go
api/clients/buckets/bucket_test.go

chore: Minor typo fixes

---

api/clients/automation/automation_test.go
api/clients/buckets/bucket_test.go
internal/testutils/testserver.go

Use dedicated struct with functions instead of raw map.

chore: enhance `testutils.TestServer`

---

api/clients/automation/automation.go

Fixes an error message in automation client.
Most probably a copy&paste error.

chore: fix error message in automation client

---

clients/documents/documents.go
clients/documents/documents_test.go

This PR allows the `externalId` for a document to be set during creation. Furthermore, it removes the Monaco specific concept of upsert for documents. Instead this logic is implemented within Monaco.

chore: Add externalId and remove upsert from document client

---

api/clients/documents/documents.go
clients/documents/documents.go
clients/documents/documents_test.go

This PR:
- The documents client shall permanently delete documents by also deleting the document from the trash.

feat: Also delete document from trash when deleting

---

clients/openpipeline/openpipeline.go
clients/openpipeline/openpipeline_test.go

As we are not sure if that's needed, I've removed the possiblility to filter by editable openipeline configs.
With this, all of the option structs are empty -so I've also removed them from the function signatures.

chore: removed editable option from openpipeline client methods

---

clients/documents/documents.go
clients/documents/documents_test.go

The PATCH endpoint is called immediately after POST when creating a document in order to make it public. However, it can be the case that the subsequent call to the PATCH endpoint happens to early. In this situation the API returns 404 and the call to Create fails. To make this more stable, a retry mechanism was added.

fix: make creation of public documents more robust

---

go.mod

chore: Update to go 1.23

---

clients/openpipeline/openpipeline.go
clients/openpipeline/openpipeline_test.go

With this PR the OpenPipeline client's Update method automatically retries when it receives a version conflict. This handles the case when an additional Update to a configuration is made before the results of the previous one have propagated.

feat: Retry on version conflict for OpenPipeline update

---

clients/segments/segment_test.go
clients/segments/segments.go

…yload, handle empty id passed on upsert
- Added a check to the payload of the upsert for mandatory fields `uid` and `owner`
- Added the option to set the ID to "", and do a direct create without calling get.

chore(`segments`): Add logic to handle mandatory fields in upsert method of smart client

---

clients/segments/segment_test.go
clients/segments/segments.go

To fix issue with the wrong ID provided in the payload, always overwrite it with the updating ID

fix(segments): fix issue with uid in segment payload not matching the remote uid

---

README.md

fix(slo): add slo client API clients in readme.md

---

api/response.go
api/response_test.go
clients/automation/automation.go
clients/buckets/bucket.go
clients/documents/documents.go

Adds a utility function to check if an error is an api error with status code 404

feat: introduce not-found error check

---

api/multipart_test.go

add test to cover `MultipartResponse` in `api` package
No, user changes.

fix: add test to cover `MultipartResponse` in `api` package

---

.github/workflows/semgrep.yml

Update `semgrep` to the latest release version, pined to a commit.
NO

fix: update `semgrep` and remove comment

---

api/response.go
clients/buckets/bucket.go

Fixes new linting errors, coming from https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/207
NONE

fix: address new linting errors

---

.github/PULL_REQUEST_TEMPLATE.md

Similar to https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1867, this PR simplifies the pull request template, based on the ideas presented in Google's 'Writing a Good Pull Request' article: https://developers.google.com/blockly/guides/contribute/get-started/write_a_good_pr#communicate-2
None
No

chore: Simplify PR template

---

api/rest/client.go

The current implementation resulted in a `concurrent map iteration and map write` error in the Dynatrace Terraform Provider, as `(c *Client) SetHeader(...)` could be called while the map was being read over in `(c *Client) sendWithRetries(...)`. 
Now the map is protected with a `sync.RWMutex` to prevent this. I did consider using a `sync.Map`, but decided that this was not suitable for this use case.
As the headers should be static between retries, request headers are now set in `(c *Client) acquireLockAndSendWithRetries(...)` rather than `(c *Client) sendWithRetries(...)`. This is important as `sync.RWMutex` should not be reentered by the same reader or writer.
No

fix: Prevent concurrent reads and writes of client header map

---

api/auth/auth.go
api/auth/auth_test.go
clients/factory.go

Small followup from #228 
* Streamlined the function names to not be `based` on something, but just be that thing
* Improved the documentation - removed unnecessary comments.
N/A
N/A
Better documentation is always good :)

refactor: Improve documentation and streamline function names

---

clients/automation/automation.go

There are some sonar issues coming from https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/223. This PR fixes those and aligns all error messages that are returned.
- Function complexity reduced
- Duplications reduced
- Adapted interfaces
- Aligned error messages
- listResponse correctly represents the response now
- split List into another listPage, to reduce complexity
- moved some errors into constants and wrappers
- by aligning error messages (same structure)
Current tests already cover it.
Doesn't affect users.
We could handle the `wfAdminAccess` differently, by returning a custom error and checking this one in the List function (`if errors.As(err, &ErrWfAdminForbidden)` then set `wfAdmin` to `false`. How about this solution?

refactor(automation): fix Sonar and error message issues

---

clients/settings/permissions/permissions.go
clients/settings/permissions/permissions_test.go

The `adminAccess` query parameter was added to support fetching permissions of different owners. When it is set to `true` and permission is given to `settings:objects:admin`, the requester is seen as the owner of the setting.
A new `adminAccess` parameter is added to all permission calls.
Existing tests are adapted to check for the existence of the `adminAccess` query parameter.
The parameters for permission calls have changed. Now the `adminAccess` query parameter has to be provided.
**Issue:** CA-15757

feat(settings): support adminAccess query param
